### ISSUE TITLE
Automations from text sensor

### ISSUE THREAD

**Issue by dakweenduck** [Chreece/FaceRec_ESPHome#2]
Hi , 

Thanks for this integration it's really useful.

What seems like a simple issue I just cant spot it and probably will slap myself:) . Since the text sensors don't update the latest value to HA if different to  previous I'm trying to use  using a 'event' to to do this to use in HA automations:

Here is the code:

```
      - id: presence_sensor
        name: "internal_presense_sensor_to_binary_template"
        internal: false
        on_value:
          - binary_sensor.template.publish:
             id: presence_template
             state: !lambda return x == "on";

          - homeassistant.event:
               event: esphome.face_recognition_scan_matched
               data:
                  title: Test Presense
               data_template:
                 user_id: User ID is {{ my_variableha1 }}
                 reply:   Reply is {{ my_variableha2 }}
                 presense: Presense is {{ my_variableha3 }}
                 presense2: Presense is {{ my_variableha4 }}

               variables:
                 my_variableha1: |-
                       !lambda 'return user_id_template;'
                 my_variableha2: |-
                       !lambda 'return reply_template;'
                 my_variableha3: |-
                       !lambda 'return x;'
                 my_variableha4: |-
                       "{{ states.presence_template.state }}"
```

The event is firing but the value passed in data template is the lambda command string and not value:)

```
event_type: esphome.face_recognition_scan_matched
data:
  device_id: d3dff94d2e3789efe17dbc18fbce28e9
  title: Test Presense
  user_id: User ID is !lambda 'return user_id_template;'
  reply: Reply is !lambda 'return reply_template;'
  presense: Presense is !lambda 'return x;'
  presense2: Presense is "{{ states.presence_template.state }}"
origin: LOCAL
time_fired: "2023-11-25T04:03:30.982517+00:00"
context:
  id: 01HG2AB6H6CWFZ1DJ9TXPXP1RW
  parent_id: null
  user_id: null
```
